export const TASKS = [
        {
      id: 'task-1',
      userId: 'user-1',
      title: "Master Angular",
      description: "Learn the basics of Angular and build a simple app.",
      completed: false,
      dueDate: '2025-12-31',
    },
    {
      id: 'task-2',
      userId: 'user-1',
      title: "Master React",
      description: "Learn the basics of React and build a simple app.",
      completed: true,
      dueDate: '2023-12-31',
    },
    {
      id: 'task-3',
      userId: 'user-2',
      title: "Develop a Mobile App",
      description: "Create a mobile app using Flutter or React Native.",
      completed: true,
      dueDate: '2025-12-31',
    },
    {
      id: 'task-4',
      userId: 'user-3',
      title: "Learn Best Practices in Software Development",
      description: "Study design patterns, testing, and code quality to become a better developer.",
      completed: false,
      dueDate: '2024-10-21',
    },
    {
      id: 'task-5',
      userId: 'user-3',
      title: "Master Angular",
      description: "Learn the basics of Angular and build a simple app.",
      completed: false,
      dueDate: '2025-12-31',
    },
    {
      id: 'task-6',
      userId: 'user-3',
      title: "Develop a Mobile App",
      description: "Create a mobile app using Flutter or React Native.",
      completed: true,
      dueDate: '2025-11-01',
    },
    {
      id: 'task-7',
      userId: 'user-4',
      title: "Master Angular",
      description: "Learn the basics of Angular and build a simple app.",
      completed: false,
      dueDate: '2025-12-31',
    },
    {
      id: 'task-8',
      userId: 'user-6',
      title: "Master C#",
      description: "Learn the basics of C# and build a simple console application.",
      completed: true,
      dueDate: '2023-05-10',
    },
    {
      id: 'task-9',
      userId: 'user-3',
      title: "Master JavaScript",
      description: "Learn the basics of JavaScript and build a simple web application.",
      completed: true,
      dueDate: '2025-12-31',
    },
    {
      id: 'task-10',
      userId: 'user-2',
      title: "Construct a Personal Portfolio Website",
      description: "Build a personal portfolio website to showcase your projects and skills.",
      completed: true,
      dueDate: '2022-02-20',
    },
]